//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>AwardsPage</summary>
	[PublishedContentModel("awardsPage")]
	public partial class AwardsPage : PublishedContentModel, IContentComposition, IHideInNav, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "awardsPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AwardsPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AwardsPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Best design bodytext
		///</summary>
		[ImplementPropertyType("bestDesignBodytext")]
		public string BestDesignBodytext
		{
			get { return this.GetPropertyValue<string>("bestDesignBodytext"); }
		}

		///<summary>
		/// Best design headline
		///</summary>
		[ImplementPropertyType("bestDesignHeadline")]
		public string BestDesignHeadline
		{
			get { return this.GetPropertyValue<string>("bestDesignHeadline"); }
		}

		///<summary>
		/// Best design list
		///</summary>
		[ImplementPropertyType("bestDesignList")]
		public IEnumerable<string> BestDesignList
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("bestDesignList"); }
		}

		///<summary>
		/// Best Editing bodytext
		///</summary>
		[ImplementPropertyType("bestEditingBodytext")]
		public string BestEditingBodytext
		{
			get { return this.GetPropertyValue<string>("bestEditingBodytext"); }
		}

		///<summary>
		/// Best Editing headline
		///</summary>
		[ImplementPropertyType("bestEditingHeadline")]
		public string BestEditingHeadline
		{
			get { return this.GetPropertyValue<string>("bestEditingHeadline"); }
		}

		///<summary>
		/// Best Editing list
		///</summary>
		[ImplementPropertyType("bestEditingList")]
		public IEnumerable<string> BestEditingList
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("bestEditingList"); }
		}

		///<summary>
		/// Best Package bodytext
		///</summary>
		[ImplementPropertyType("bestPackageBodytext")]
		public string BestPackageBodytext
		{
			get { return this.GetPropertyValue<string>("bestPackageBodytext"); }
		}

		///<summary>
		/// Best Package headline
		///</summary>
		[ImplementPropertyType("bestPackageHeadline")]
		public string BestPackageHeadline
		{
			get { return this.GetPropertyValue<string>("bestPackageHeadline"); }
		}

		///<summary>
		/// Best Package list
		///</summary>
		[ImplementPropertyType("bestPackageList")]
		public IEnumerable<string> BestPackageList
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("bestPackageList"); }
		}

		///<summary>
		/// Technical Solution bodytext
		///</summary>
		[ImplementPropertyType("technicalSolutionBodytext")]
		public string TechnicalSolutionBodytext
		{
			get { return this.GetPropertyValue<string>("technicalSolutionBodytext"); }
		}

		///<summary>
		/// Technical Solution list
		///</summary>
		[ImplementPropertyType("technicalSolutionCheckboxes")]
		public IEnumerable<string> TechnicalSolutionCheckboxes
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("technicalSolutionCheckboxes"); }
		}

		///<summary>
		/// Technical Solution Headline
		///</summary>
		[ImplementPropertyType("technicalSolutionHeadline")]
		public string TechnicalSolutionHeadline
		{
			get { return this.GetPropertyValue<string>("technicalSolutionHeadline"); }
		}

		///<summary>
		/// Bodytext
		///</summary>
		[ImplementPropertyType("bodytext")]
		public string Bodytext
		{
			get { return Umbraco.Web.PublishedContentModels.ContentComposition.GetBodytext(this); }
		}

		///<summary>
		/// Content image
		///</summary>
		[ImplementPropertyType("contentImage")]
		public IPublishedContent ContentImage
		{
			get { return Umbraco.Web.PublishedContentModels.ContentComposition.GetContentImage(this); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.ContentComposition.GetHeadline(this); }
		}

		///<summary>
		/// Hide in umbraco navigation
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideInNav.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Meta description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaKeywords(this); }
		}
	}
}
