//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Award Unit</summary>
	[PublishedContentModel("awardUnit")]
	public partial class AwardUnit : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "awardUnit";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AwardUnit(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AwardUnit, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Vote Count: Do not edit this field - Important
		///</summary>
		[ImplementPropertyType("voteCount")]
		public int VoteCount
		{
			get { return this.GetPropertyValue<int>("voteCount"); }
		}

		///<summary>
		/// Website Creator
		///</summary>
		[ImplementPropertyType("websiteCreator")]
		public string WebsiteCreator
		{
			get { return this.GetPropertyValue<string>("websiteCreator"); }
		}

		///<summary>
		/// Website Domain
		///</summary>
		[ImplementPropertyType("websiteDomain")]
		public string WebsiteDomain
		{
			get { return this.GetPropertyValue<string>("websiteDomain"); }
		}

		///<summary>
		/// Website Picture
		///</summary>
		[ImplementPropertyType("websitePicture")]
		public IPublishedContent WebsitePicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("websitePicture"); }
		}
	}
}
