//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>BlockListItem</summary>
	[PublishedContentModel("blockListItem")]
	public partial class BlockListItem : PublishedContentModel, ILinkBlock, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blockListItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlockListItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlockListItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link block bodytext
		///</summary>
		[ImplementPropertyType("linkBlockBodytext")]
		public IHtmlString LinkBlockBodytext
		{
			get { return Umbraco.Web.PublishedContentModels.LinkBlock.GetLinkBlockBodytext(this); }
		}

		///<summary>
		/// Link block headline
		///</summary>
		[ImplementPropertyType("linkBlockHeadline")]
		public string LinkBlockHeadline
		{
			get { return Umbraco.Web.PublishedContentModels.LinkBlock.GetLinkBlockHeadline(this); }
		}

		///<summary>
		/// Link block image
		///</summary>
		[ImplementPropertyType("linkBlockImage")]
		public IPublishedContent LinkBlockImage
		{
			get { return Umbraco.Web.PublishedContentModels.LinkBlock.GetLinkBlockImage(this); }
		}

		///<summary>
		/// Meta description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaKeywords(this); }
		}
	}
}
