//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1060 with alias "contentComposition"
	/// <summary>Content composition</summary>
	public partial interface IContentComposition : IPublishedContent
	{
		/// <summary>Bodytext</summary>
		string Bodytext { get; }

		/// <summary>Content image</summary>
		IPublishedContent ContentImage { get; }

		/// <summary>Headline</summary>
		string Headline { get; }
	}

	/// <summary>Content composition</summary>
	[PublishedContentModel("contentComposition")]
	public partial class ContentComposition : PublishedContentModel, IContentComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentComposition";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentComposition(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentComposition, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Bodytext
		///</summary>
		[ImplementPropertyType("bodytext")]
		public string Bodytext
		{
			get { return GetBodytext(this); }
		}

		/// <summary>Static getter for Bodytext</summary>
		public static string GetBodytext(IContentComposition that) { return that.GetPropertyValue<string>("bodytext"); }

		///<summary>
		/// Content image
		///</summary>
		[ImplementPropertyType("contentImage")]
		public IPublishedContent ContentImage
		{
			get { return GetContentImage(this); }
		}

		/// <summary>Static getter for Content image</summary>
		public static IPublishedContent GetContentImage(IContentComposition that) { return that.GetPropertyValue<IPublishedContent>("contentImage"); }

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return GetHeadline(this); }
		}

		/// <summary>Static getter for Headline</summary>
		public static string GetHeadline(IContentComposition that) { return that.GetPropertyValue<string>("headline"); }
	}
}
