//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>DiscoverpageChecklist</summary>
	[PublishedContentModel("discoverpageChecklist")]
	public partial class DiscoverpageChecklist : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "discoverpageChecklist";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DiscoverpageChecklist(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DiscoverpageChecklist, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Discover checklist bodytext
		///</summary>
		[ImplementPropertyType("discoverChecklistBodytext")]
		public IHtmlString DiscoverChecklistBodytext
		{
			get { return this.GetPropertyValue<IHtmlString>("discoverChecklistBodytext"); }
		}

		///<summary>
		/// Discover checklist headline
		///</summary>
		[ImplementPropertyType("discoverChecklistHeadline")]
		public string DiscoverChecklistHeadline
		{
			get { return this.GetPropertyValue<string>("discoverChecklistHeadline"); }
		}
	}
}
