//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Frontpage</summary>
	[PublishedContentModel("frontpage")]
	public partial class Frontpage : PublishedContentModel, IContentComposition, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "frontpage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Frontpage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Frontpage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Event description
		///</summary>
		[ImplementPropertyType("eventDescription")]
		public IHtmlString EventDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("eventDescription"); }
		}

		///<summary>
		/// Event image
		///</summary>
		[ImplementPropertyType("eventImage")]
		public IPublishedContent EventImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("eventImage"); }
		}

		///<summary>
		/// Event link
		///</summary>
		[ImplementPropertyType("eventLink")]
		public IPublishedContent EventLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("eventLink"); }
		}

		///<summary>
		/// Event link secondary
		///</summary>
		[ImplementPropertyType("eventLinkSecondary")]
		public IPublishedContent EventLinkSecondary
		{
			get { return this.GetPropertyValue<IPublishedContent>("eventLinkSecondary"); }
		}

		///<summary>
		/// Event list text
		///</summary>
		[ImplementPropertyType("eventListText")]
		public IHtmlString EventListText
		{
			get { return this.GetPropertyValue<IHtmlString>("eventListText"); }
		}

		///<summary>
		/// Help yourself bodytext
		///</summary>
		[ImplementPropertyType("helpYourselfBodytext")]
		public string HelpYourselfBodytext
		{
			get { return this.GetPropertyValue<string>("helpYourselfBodytext"); }
		}

		///<summary>
		/// Help yourself headline
		///</summary>
		[ImplementPropertyType("helpYourselfHeadline")]
		public string HelpYourselfHeadline
		{
			get { return this.GetPropertyValue<string>("helpYourselfHeadline"); }
		}

		///<summary>
		/// Help yourself image
		///</summary>
		[ImplementPropertyType("helpYourselfImage")]
		public IPublishedContent HelpYourselfImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("helpYourselfImage"); }
		}

		///<summary>
		/// Help yourself link
		///</summary>
		[ImplementPropertyType("helpYourselfLink")]
		public IPublishedContent HelpYourselfLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("helpYourselfLink"); }
		}

		///<summary>
		/// Bodytext
		///</summary>
		[ImplementPropertyType("bodytext")]
		public string Bodytext
		{
			get { return Umbraco.Web.PublishedContentModels.ContentComposition.GetBodytext(this); }
		}

		///<summary>
		/// Content image
		///</summary>
		[ImplementPropertyType("contentImage")]
		public IPublishedContent ContentImage
		{
			get { return Umbraco.Web.PublishedContentModels.ContentComposition.GetContentImage(this); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.ContentComposition.GetHeadline(this); }
		}

		///<summary>
		/// Meta description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaKeywords(this); }
		}
	}
}
